version: '3.8'

services:
  secure-dns-web:
    build: .
    container_name: secure-dns-web
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "80:80"
      - "443:443"
    volumes:
      - knot-data:/var/lib/knot
      - apache-data:/var/www/html
      - letsencrypt-data:/etc/letsencrypt
    restart: unless-stopped
    networks:
      app_network:
        ipv4_address: 172.28.43.45 # Match your configuration

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.43.0/24

volumes:
  knot-data:
  apache-data:
  letsencrypt-data: